// <auto-generated />
using System;
using ArchitectureClean.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArchitectureClean.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ArchitectureClean.Domain.Entities.Administrador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("ArchitectureClean.Domain.Entities.Estagiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Estagiarios");
                });

            modelBuilder.Entity("ArchitectureClean.Domain.Entities.Frequencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Abono")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime>("DataChegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EstagiarioId")
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("HoraChegada")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraSaida")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("EstagiarioId");

                    b.ToTable("Frequencias");
                });

            modelBuilder.Entity("ArchitectureClean.Domain.Entities.Administrador", b =>
                {
                    b.OwnsOne("ArchitectureClean.Domain.ValueObject.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("AdministradorId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Email");

                            b1.HasKey("AdministradorId");

                            b1.ToTable("Administradores");

                            b1.WithOwner()
                                .HasForeignKey("AdministradorId");
                        });

                    b.OwnsOne("ArchitectureClean.Domain.ValueObject.Senha", "Senha", b1 =>
                        {
                            b1.Property<Guid>("AdministradorId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("SenhaHash");

                            b1.HasKey("AdministradorId");

                            b1.ToTable("Administradores");

                            b1.WithOwner()
                                .HasForeignKey("AdministradorId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Senha")
                        .IsRequired();
                });

            modelBuilder.Entity("ArchitectureClean.Domain.Entities.Frequencia", b =>
                {
                    b.HasOne("ArchitectureClean.Domain.Entities.Estagiario", "Estagiario")
                        .WithMany()
                        .HasForeignKey("EstagiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estagiario");
                });
#pragma warning restore 612, 618
        }
    }
}
